# --- PPO specific parameters ---
action_selector: "multinomial"
epsilon_start: .5
epsilon_finish: .01
epsilon_anneal_time: 100000
mask_before_softmax: True

runner: "parallel"

buffer_size: 8
batch_size_run: 8
batch_size: 8

# update the target network every {} training steps
target_update_interval: 200

lr_actor: 0.0005
lr_critic: 0.001
tau: 0.995
td_lambda: 0.99

agent_output_type: "pi_logits"
learner: "trust_region_learner"
critic: "centralV_rnn_critic"

# for rnn training
detach_every: 20
replace_every: null

mini_epochs_actor: 10
mini_epochs_critic: 10
entropy_loss_coeff: 0.000

# calculating advantage: GAE, TD_Error
advantage_calc_method: "GAE"
bootstrap_timeouts: False

surrogate_clipped: True
clip_range: 0.1
trust_region_constraint: 'none'

is_advantage_normalized: True
is_observation_normalized: True
is_popart: False
is_value_normalized: False

obs_agent_id: True
obs_last_action: False

name: "ppo_rnn_central_V"